export const unitCosts = {
    "tft3_ahri": 2,
    "tft3_annie": 2,
    "tft3_ashe": 3,
    "tft3_aurelionsol": 5,
    "tft3_bard": 3,
    "tft3_blitzcrank": 2,
    "tft3_caitlyn": 1,
    "tft3_cassiopeia": 3,
    "tft3_darius": 2,
    "tft3_ekko": 5,
    "tft3_ezreal": 3,
    "tft3_fiora": 1,
    "tft3_fizz": 4,
    "tft3_gangplank": 5,
    "tft3_gnar": 4,
    "tft3_graves": 1,
    "tft3_illaoi": 1,
    "tft3_irelia": 4,
    "tft3_janna": 5,
    "tft3_jarvaniv": 1,
    "tft3_jayce": 3,
    "tft3_jhin": 4,
    "tft3_jinx": 4,
    "tft3_karma": 3,
    "tft3_kogmaw": 2,
    "tft3_leona": 1,
    "tft3_lucian": 2,
    "tft3_lulu": 5,
    "tft3_malphite": 1,
    "tft3_masteryi": 3,
    "tft3_mordekaiser": 2,
    "tft3_nautilus": 2,
    "tft3_neeko": 3,
    "tft3_nocturne": 1,
    "tft3_poppy": 1,
    "tft3_rakan": 2,
    "tft3_riven": 4,
    "tft3_rumble": 3,
    "tft3_shaco": 3,
    "tft3_shen": 2,
    "tft3_soraka": 4,
    "tft3_syndra": 3,
    "tft3_teemo": 4,
    "tft3_thresh": 5,
    "tft3_twistedfate": 1,
    "tft3_urgot": 5,
    "tft3_vayne": 3,
    "tft3_vi": 3,
    "tft3_viktor": 4,
    "tft3_wukong": 4,
    "tft3_xayah": 1,
    "tft3_xerath": 5,
    "tft3_xinzhao": 2,
    "tft3_yasuo": 2,
    "tft3_zed": 2,
    "tft3_ziggs":1 ,
    "tft3_zoe": 1
}

export const oneCostColor = '#213042';
export const twoCostColor = '#156831';
export const threeCostColor = '#12407c';
export const fourCostColor = '#893088';
export const fiveCostColor = '#b89d27';